# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nc10VwE3892qUOr4rPIJT854DP4WjUiK
"""

import streamlit as st
from transformers import pipeline

# Page config
st.set_page_config(page_title="Emotion Classifier", page_icon="🧠")

st.title("🧠 Emotion Classifier")
st.caption("Fine-tuned DistilBERT · Built by Shweta Koyande")

# Load model — cached so it doesn't reload every interaction
@st.cache_resource
def load_model():
    return pipeline(
        "text-classification",
        model="bhadresh-savani/distilbert-base-uncased-emotion",
        return_all_scores=True
    )

classifier = load_model()

# Input
st.subheader("Enter any text:")
user_input = st.text_area("", placeholder="Type something emotional here...", height=100)

if st.button("Classify Emotion"):
    if user_input.strip():
        with st.spinner("Analyzing..."):
            output = classifier(user_input)
            # Handle both list-of-dicts and single dict responses
            results = output[0] if isinstance(output[0], list) else output
            results = sorted(results, key=lambda x: x['score'], reverse=True)

        st.subheader("Results:")
        # Show top emotion prominently
        top = results[0]
        emotion_emoji = {"joy":"😊","sadness":"😢","anger":"😠","fear":"😨","love":"❤️","surprise":"😲"}
        emoji = emotion_emoji.get(top['label'], "🤔")
        st.metric(f"{emoji} Top Emotion", top['label'].upper(), f"{top['score']:.1%} confidence")

        # Show all scores as bars
        st.subheader("All emotions:")
        for r in results:
            st.write(f"**{r['label']}**")
            st.progress(r['score'])
            st.caption(f"{r['score']:.1%}")
    else:
        st.warning("Please enter some text first.")

# Sidebar with your info
with st.sidebar:
    st.header("About this app")
    st.write("Built during AI/ML portfolio development.")
    st.write("**Model:** DistilBERT fine-tuned on emotion dataset")
    st.write("**Classes:** Joy, Sadness, Anger, Fear, Love, Surprise")
    st.markdown("---idlo")
    st.write("Try inputs like:")
    st.code("I can't believe how well this worked!")
    st.code("I'm really nervous about the interview.")
    st.code("This is deeply unfair and frustrating.")

#streamlit run app.py