# -*- coding: utf-8 -*-
"""finetuning_day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwokpYbU18PVHwoCHRybutZyVFqiFSDA
"""

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.utils.data import DataLoader
from torch.optim import AdamW
import torch

# Load a tiny real dataset — emotion classification
dataset = load_dataset("emotion", split="train[:500]")  # just 500 samples to keep it fast
val_data = load_dataset("emotion", split="validation[:100]")

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch["text"], padding=True, truncation=True, max_length=64)

dataset = dataset.map(tokenize, batched=True)
val_data = val_data.map(tokenize, batched=True)

dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_data.set_format("torch", columns=["input_ids", "attention_mask", "label"])

train_loader = DataLoader(dataset, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_data, batch_size=16)

# 6 emotion classes: sadness, joy, love, anger, fear, surprise
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=6)
optimizer = AdamW(model.parameters(), lr=2e-5)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# ── TRAINING LOOP ──
for epoch in range(2):
    model.train()
    total_loss = 0
    for batch in train_loader:
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels         = batch["label"].to(device)

        outputs = model(input_ids=input_ids,
                        attention_mask=attention_mask,
                        labels=labels)
        loss = outputs.loss
        total_loss += loss.item()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1} | Avg Loss: {total_loss/len(train_loader):.4f}")

# ── EVALUATION ──
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for batch in val_loader:
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels         = batch["label"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        preds = outputs.logits.argmax(dim=-1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

print(f"\nValidation Accuracy: {correct/total:.2%}")