# -*- coding: utf-8 -*-
"""hf_day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrkCCwiyK6BdGvsds8bKD3pbdm5reaVf
"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load the actual model components — not just the pipeline wrapper
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

sentences = [
    "Adversarial attacks expose critical vulnerabilities in language models.",
    "The fairness-aware model reduced gender bias significantly.",
    "This approach fails to generalize beyond the training distribution."
]

# Tokenize manually so you SEE what the model actually receives
inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")
print("Input IDs shape:", inputs['input_ids'].shape)
print("Tokens for sentence 1:", tokenizer.convert_ids_to_tokens(inputs['input_ids'][0]))

# Forward pass
with torch.no_grad():
    outputs = model(**inputs)
    predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)

labels = ["NEGATIVE", "POSITIVE"]
for i, sentence in enumerate(sentences):
    pred = predictions[i]
    print(f"\n'{sentence[:50]}...'")
    print(f"  → {labels[pred.argmax()]} (confidence: {pred.max():.3f})")