# -*- coding: utf-8 -*-
"""Learning Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHUHaJiajufyo9Ycp7TBnHZzjcyL7XSD
"""

from transformers import pipeline

# Sentiment — same family as your adversarial work
classifier = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english")

results = classifier([
    "This model is incredibly robust under adversarial conditions.",
    "The recommendation system failed to account for gender bias.",
    "Transformers have completely changed NLP research."
])

for r in results:
    print(r)
# ```

# Run it. See it work. That's it. This is the same Hugging Face ecosystem you used in your MS project — you're just re-meeting it. Save this as `hf_day2.py` in your repo and commit.

# **3 commits this week = good. Consistency > volume.**

# ---

# ## 📅 Course Schedule (Next 6 Weeks)

# Here's the exact plan so you're never guessing:

# | Week | Course | Daily Time | Purpose |
# |------|--------|-----------|---------|
# | **1–2** (now) | Andrew Ng ML Specialization — Coursera | 45 mins/day | Re-anchor ML vocabulary + interview language |
# | **3–4** | LangChain + LLM Apps — Udemy (Eden Marco) | 60 mins/day | Fill your biggest gap: RAG + LLM engineering |
# | **5–6** | PyTorch for Deep Learning — Udemy (ZTM) | 60 mins/day | Strengthen PyTorch (your TF is stronger right now) |
# | **Ongoing** | Hugging Face free NLP course | 30 mins/day | Free cert + directly relevant to your existing projects |

# The remaining 60–90 mins each day is always for **building** — projects, deployment, GitHub commits.

# ---

# ## The Simple Daily Structure Going Forward
# ```
# Day start  →  15 mins: re-read yesterday's code/notes (memory anchor)
# Block 1    →  60 mins: course (video + follow along in code)
# Block 2    →  60–90 mins: project / hands-on building
# End        →  5 mins: commit to GitHub, write one line in a daily-log.md