# -*- coding: utf-8 -*-
"""RAG_learning_day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiYjIYgwlQLVogbPR_-cS-NbL64nOVZC
"""

!pip install -q -U langchain langchain-community langchain-text-splitters \
             chromadb sentence-transformers tiktoken transformers torch

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from transformers import pipeline as hf_pipeline

research_text = """
Adversarial attacks on large language models represent a critical vulnerability
in modern NLP systems. The Greedy Coordinate Gradient (GCG) attack works by
iteratively searching for token substitutions that maximize the probability of
harmful model outputs. Our experiments achieved 100% attack success rate on
DistilBERT and BERT-base models in controlled settings.

Defense mechanisms include adversarial training, input preprocessing, and
detection-based approaches. Our proposed defense achieved 98% mitigation success
by combining input smoothing with adversarial fine-tuning.

The fairness-aware recommendation system used orthogonal regularization within
a GAN framework to reduce gender bias by 56.5% while maintaining competitive
recommendation accuracy measured by AUC, MRR, and nDCG metrics.

Transformer models use attention mechanisms to weigh the relevance of each token
relative to others. The query, key, and value matrices determine how information
flows between tokens during both encoding and decoding phases.
"""

# Chunk + deduplicate
splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=40)
chunks = list(dict.fromkeys(splitter.split_text(research_text)))  # dedup here
docs = [Document(page_content=chunk) for chunk in chunks]
print(f"✅ {len(docs)} unique chunks")
for i, d in enumerate(docs):
    print(f"  Chunk {i+1}: {d.page_content[:80]}...")

print("Loading embeddings...")
embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2",
    model_kwargs={"device": "cpu"}
)
vectorstore = Chroma.from_documents(docs, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 2})
print("✅ Vectorstore ready")

print("Loading TinyLlama... (2-3 mins)")
generator = hf_pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    max_new_tokens=150,
    do_sample=False,
    device=-1
)
print("✅ Generator ready")

def ask(question, verbose=True):
    """
    RAG pipeline:
    1. Embed question → find similar chunks
    2. Feed chunks as context to LLM
    3. LLM answers using only that context
    """
    retrieved = retriever.invoke(question)

    if verbose:
        print(f"  Retrieved {len(retrieved)} chunks:")
        for i, d in enumerate(retrieved):
            print(f"  [{i+1}] {d.page_content[:100]}...")

    context = "\n".join([d.page_content for d in retrieved])

    prompt = f"""<|system|>
Answer only using the context below. Be specific and concise.</s>
<|user|>
Context: {context}

Question: {question}</s>
<|assistant|>"""

    output = generator(prompt, max_new_tokens=150)[0]["generated_text"]
    answer = output.split("<|assistant|>")[-1].strip()
    return answer

ask("How does the GCG attack work?")

ask("What fairness metric improved and by how much?")

ask("What are query key and value in transformers?")

from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline as hf_pipeline

print("Loading answer generation model... (2-3 mins)")

generator = hf_pipeline(
    "text-generation",          # ← changed
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",  # ← small, free, fast
    max_new_tokens=150,
    do_sample=False,
    device=-1
)

llm = HuggingFacePipeline(pipeline=generator)
retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

print("✅ Ready!\n")

def ask_with_answer(question):
    # Retrieve relevant chunks
    relevant_chunks = retriever.invoke(question)
    context = "\n".join([doc.page_content for doc in relevant_chunks])

    # Build prompt
    prompt = f"""<|system|>
You are a helpful assistant. Answer only using the context provided.</s>
<|user|>
Context: {context}

Question: {question}</s>
<|assistant|>"""

    # Generate
    raw = generator(prompt, max_new_tokens=100)[0]["generated_text"]

    # Extract just the answer part after <|assistant|>
    answer = raw.split("<|assistant|>")[-1].strip()

    print(f"❓ {question}")
    print(f"🤖 {answer}")
    print(f"📄 From chunk: {relevant_chunks[0].page_content[:100]}...")
    print("-" * 60)

ask_with_answer("What was the success rate of the defense mechanism?")

ask_with_answer("How does the GCG attack find adversarial tokens?")

ask_with_answer("What fairness metric improved and by how much?")

questions = [
    "What attack method did you use?",
    "What was the adversarial attack success rate?",
    "How did you defend against the adversarial attack?",
    "What percentage did gender bias reduce by?",
    "What are query key and value in attention?"
]

print("=" * 60)
for i, q in enumerate(questions):
    print(f"\nQ{i+1}: {q}")
    answer = ask(q, verbose=True)
    print(f"A{i+1}: {answer}")
    print("=" * 60)